### ISSUE TITLE
Documentation and README.md is outdated which affects discoverablity of features!

### ISSUE THREAD

**Issue by aspizu** [aspizu/goboscript#16]

**Comment by stefania11** [comment]
I am really struggling with your installation instructions could you please update readme? @aspizu thank you!

**Comment by aspizu** [comment]
What issue are you having?

**Comment by stefania11** [comment]
These commands don't work for python3/pip3 

cd ~/Downloads/SRC
pip install lark
git clone https://github.com/aspizu/goboscript
cd goboscript
echo -e "#\!/bin/bash\nset -e\npython $(pwd)/gsc \"\$@\"" > ~/.local/bin/gsc
chmod +x ~/.local/bin/gsc

In particular I recommend replacing this command with something more legible and easier to adapt for different python versions 
echo -e "#\!/bin/bash\nset -e\npython $(pwd)/gsc \"\$@\"" > ~/.local/bin/gsc

**Comment by aspizu** [comment]
If you are on debian/ubuntu install `python3-is-python`

**Comment by stefania11** [comment]
following your readme commands I get the following error 

"zsh: no such file or directory: /Users/stef/.local/bin/gsc"

**Comment by aspizu** [comment]
run this inside where you have cloned the repository
```
mkdir -p ~/.bin
echo -e "#!/bin/bash\nset -e\npython3 "'"$(pwd)"' > ~/.bin/gsc
chmod +x ~/.bin/gsc
echo -e "path+=(~/.bin)" >> ~/.zshrc
```
