### ISSUE TITLE
How do i install gsc compiler

### ISSUE THREAD

**Issue by HGT-123** [aspizu/goboscript#18]
Im stuck... running wsl kali linux and cant install gsc

**Comment by aspizu** [comment]
Did you follow the instructions in the `README.md`?
What commands did you run and what was the output?

**Comment by HGT-123** [comment]
Uhh im using wsl so i dont have a full desktop filesystem so the bash commands to install it dont work

**Comment by aspizu** [comment]
answer my questions

**Comment by Poly2it** [comment]
> Uhh im using wsl so i dont have a full desktop filesystem so the bash commands to install it dont work

Commands
```
cd ~/Downloads/SRC
pip install lark
git clone https://github.com/aspizu/goboscript
cd goboscript
echo -e "#\!/bin/bash\nset -e\npython $(pwd)/gsc \"\$@\"" > ~/.local/bin/gsc
chmod +x ~/.local/bin/gsc
```
