### ISSUE TITLE
Ceil Block does not work

### ISSUE THREAD

**Issue by LoganAbel** [aspizu/goboscript#30]
`ceil (2.5)` in goboscript produced the following block:

<img width="77" alt="image" src="https://github.com/aspizu/goboscript/assets/106107469/00b980f7-0f4b-4087-bf5d-17785586b1d7">

Instead, "ceiling of" should be produced like this:

<img width="90" alt="image" src="https://github.com/aspizu/goboscript/assets/106107469/0f323723-2ddb-4e08-a34a-16358b66d171">

I think this might be an issue with `line 82` of `goboscript / src / blocks.rs` : `Self::Ceil => Some("{\"OPERATOR\": [\"ceil\", null]}"),`

**Comment by aspizu** [comment]
https://github.com/aspizu/goboscript/blob/b2c4c8711084c1fbc1c432f80919f2f299a9a3c6/gdsl.txt#L10

Change `...=ceil` to `...=ceiling`, then run `gdsl.py` from root of repository.

**Comment by LoganAbel** [comment]
Thanks, that worked

**Comment by aspizu** [comment]
could you make a PR?
